### ISSUE TITLE
trying to create exam, but after i hit create it just doesnt do anything, help please ? 

### ISSUE THREAD

**Issue by Elunion** [mshossain110/examinee#10]

**Comment by Mastersam07** [comment]
I'm also experiencing this issue @mshossain110

**Comment by mshossain110** [comment]
there was an issue. I just fixed it. Please give me some time. Major changes coming with new laravel.

**Comment by Mastersam07** [comment]
Okay. I guess the next PR or release should fix it?

**Comment by mshossain110** [comment]
Hello, I push into develop.  you can pull now. I upgrade the application to Laravel 7. So please reinstall the app and follow installation process again.

**Comment by Mastersam07** [comment]
Okay. Will try it out now

**Comment by harshitbhatt26** [comment]
1) As I follow all the step which you mention but then also not able get the view which you shown in project screen shot.
2) Even I am not able to create exam nothing is happen when create exam.

![1_Exam Management](https://user-images.githubusercontent.com/64131479/79960839-87236180-84a3-11ea-83af-15095a19469f.png)
![2_Exam Management](https://user-images.githubusercontent.com/64131479/79960845-88ed2500-84a3-11ea-9d84-23d6fc41cd0c.png)

**Comment by mshossain110** [comment]
Hello, @harshitbhatt26 have you pulled the last two commits. exam creating issue I fixed in my last commit.

**Comment by harshitbhatt26** [comment]
> Hello, @harshitbhatt26 have you pulled the last two commits. exam creating issue I fixed in my last commit.

Can you please give me that link so, from their i will get or given me completed product link so, i can check it.

**Comment by Mastersam07** [comment]
@harshitbhatt26 I think what @mshossain110 is saying is that you should cd into the project root directory and run `git pull` to pull the new changes/files. This would work if you git clone the project else you will have to re-download the project again and follow the setup instructions.
