### ISSUE TITLE
Not properly run

### ISSUE THREAD

**Issue by Mastersam07** [mshossain110/examinee#11]
I followed the instruction and the app just seems to be a raw HTML skeleton without styles. Attached is a screenshot of the app view and my command line after running npm run watch

![Screenshot (419)](https://user-images.githubusercontent.com/31275429/79425872-3083c800-7f77-11ea-8ee1-c0e366540c52.png)
![Screenshot (418)](https://user-images.githubusercontent.com/31275429/79425879-324d8b80-7f77-11ea-95fa-603c425976e4.png)

**Comment by Mastersam07** [comment]
What's the proper way to run the app and see the results on the browser? after running npm run watch?

**Comment by Mastersam07** [comment]
Also the sample data in the database, I cant seem to login to any of them. How do I get their login details? The passwords are hashed in the database

**Comment by mshossain110** [comment]
Hello, 
Thank you for using this application. 
can you tell me why are you browsing server.php? I think you are wrong there. 

if you are not sure then open another terminal then write the comment `php artisan serve`.  this will start your server on http://127.0.0.1:8000.  then browse http://127.0.0.1:8000

Thank you

**Comment by Mastersam07** [comment]
Okay. It works fine. Thanks.
