### ISSUE TITLE
css js not found

### ISSUE THREAD

**Issue by napsterrahul1** [mshossain110/examinee#12]
css js not found

**Comment by mshossain110** [comment]
did you follow the installation process?

**Comment by napsterrahul1** [comment]
yes i do but not available in public path.
installation process folowed. can you please send css and js files from public path to me on mail
rahul@inubex.com

**Comment by mshossain110** [comment]
project build with Laravel and Vue. I think you should have some basic knowledge on those.

**Comment by napsterrahul1** [comment]
done
