### ISSUE TITLE
No Contents No Exam Management

### ISSUE THREAD

**Issue by tok3** [mshossain110/examinee#13]
I installed the app according to you installation instructions but after login as admin no data is displayed. No lessons, no students, and the menu item "courses" is not working. Maybe errors in vue scripts !?

**Comment by mshossain110** [comment]
At this moment the courses page has no data. do you see data on scholar and student page? If not see please run the seeder 
`php artisan migrate:fresh --seed`

**Comment by harshaldosh** [comment]
how to run the app

**Comment by bekelehaile** [comment]
Yes exactly , API authentication issue.

**Solution**
The sanctum stateful domains in .env file should be the same addresses of our front-end apps including the port numbers.
as the following code snippets
APP_URL=http://**localhost:8000**
SANCTUM_STATEFUL_DOMAINS=**localhost:8000**

**Comment by AbdanSFR** [comment]
what the admin pasword ?
