### ISSUE TITLE
i can't create course or quiz

### ISSUE THREAD

**Issue by abdallah84** [mshossain110/examinee#14]
i install it but i cant' create course or quiz,
and it doesn't show my courses and quizzes (the default data)
as eg. i go here to create course (http://127.0.0.1:8000/instructor/courses) 
but it gives error 
Unauthenticated.
C:\xamppphp7\htdocs\examinee\vendor\laravel\framework\src\Illuminate\Auth\Middleware\Authenticate.php#82

also how i can assign role to user ?
and assign permission to role ?

**Comment by mshossain110** [comment]
please try seeder.

**Comment by abdallah84** [comment]
the seeder is working but still the same problem

**Comment by bekelehaile** [comment]
Sanctum/api authentication issue. Necessarily front-end app(s) and band-end app(s) to be serve from the same domain
 — localhost in our case, in .env file in laravel app just put:
APP_URL=http://**localhost:8000**
SANCTUM_STATEFUL_DOMAINS=**localhost:8000**
    
NB: Besides to this some properties change maybe needed in config/cors file like support credential set to true and others.
