### ISSUE TITLE
npm run watch fail

### ISSUE THREAD

**Issue by irvadesigner** [mshossain110/examinee#19]
I followed everything and it works but last step just showed me this error. Please let me know what to do

error: unknown option '--hide-modules'
[webpack-cli] Run 'webpack --help' to see available commands and options
npm ERR! code 2
npm ERR! path /Users/elva/code/examinee
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js "--watch"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/elva/.npm/_logs/2021-01-14T14_14_19_051Z-debug.log
npm ERR! code 2
npm ERR! path /Users/elva/code/examinee
npm ERR! command failed
npm ERR! command sh -c npm run development -- --watch

**Comment by mshossain110** [comment]
Hi, I upgrade to laravel 8 and change some scripts. would you like to check again?
