### ISSUE TITLE
while migrating i have error in migration

### ISSUE THREAD

**Issue by sagar720** [mshossain110/examinee#2]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your Maria
DB server version for the right syntax to use near 'json null, `avatar` varchar(191) null, `password` varchar(191) not null, `email_' at line 1 (SQL: create table `users` (`id` bigin
t unsigned not null auto_increment primary key, `name` varchar(191) not null, `firstname` varchar(191) null, `lastname` varchar(191) null, `email` varchar(191) not null, `permissions
` json null, `avatar` varchar(191) null, `password` varchar(191) not null, `email_verified_at` timestamp null, `last_loged_in` timestamp default CURRENT_TIMESTAMP not null, `ip` varc
har(45) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null, `deleted_at` timestamp null) default character set utf8mb4 collate 'utf8mb
4_unicode_ci')

**Comment by mshossain110** [comment]
The application builds for MySQL 8, MariaDB 10 or above.  if you dose not have you should change 'json' field to 'text' field. and try to save data as json. 

Note: I am working on this project to upgrade it. You will find some more issue. don't worry. I will try to complete the project. Try to make some contribution to this project.
