### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by Rajaimaswadi** [mshossain110/examinee#3]
I have installed and configured the project, but i need sample data. Anyone can provide me with it?

**Comment by mshossain110** [comment]
Have you tried DB seeder? I added a seeder for sample data. 

`php artisan migrate --seed`

Thanks

**Comment by Rajaimaswadi** [comment]
Could you share the command to use it?

Thank you so much for your response

**Comment by key60529** [comment]
> Could you share the command to use it? Thank you so much for your response
> […](#)

`cd` to the directory of your project root and run `php artisan migrate --seed`
