### ISSUE TITLE
What problems did I encounter when I deployed the project

### ISSUE THREAD

**Issue by zijeric** [mshossain110/examinee#4]
Why is the display incomplete when starting the project ？

![issue](https://user-images.githubusercontent.com/51075500/71411448-3f6f0380-2684-11ea-9d18-4a549c2d84ac.png)

**Comment by mshossain110** [comment]
its seems that you don't compile Vue files. please install dependencies and compile Vue file `npm run watch`
I recommended following How to install section 

1. Clone the repo `git clone https://github.com/mshossain110/examinee.git`
2. Move Directory `cd examinee`
3. Install composer `composer install`
4. Copy .env file `cp .env.example .env`
5. Generate key `php artisan key:generate`
6. Create database and edit .env file to add database, MAIL_DRIVER
7. Migrate database `php artisan migrate`
8. Install npm `npm i`
9. Watch file `npm run watch`

**Comment by Nolva** [comment]
Yes, what puzzles me is that I've gone through all the steps and I can't show it.

**Comment by Nolva** [comment]
> 
> 
> Why is the display incomplete when starting the project ？
> 
> ![issue](https://user-images.githubusercontent.com/51075500/71411448-3f6f0380-2684-11ea-9d18-4a549c2d84ac.png)
