### ISSUE TITLE
Bug in registered function.

### ISSUE THREAD

**Issue by ghosttk** [mshossain110/examinee#5]
After migration and 'npm run dev'.
Submiting the register new user form throw an error.

`Argument 1 passed to App\Http\Controllers\Auth\RegisterController::registered() must be an instance of App\Http\Controllers\Auth\Request, instance of Illuminate\Http\Request given, called in /home/ww/projects/php/examinee/vendor/laravel/framework/src/Illuminate/Foundation/Auth/RegistersUsers.php on line 37`

**Comment by mshossain110** [comment]
Fixed the issue
