### ISSUE TITLE
Any plan to upgrade the Bootstrap 3 to Bootstrap 4?

### ISSUE THREAD

**Issue by key60529** [mshossain110/examinee#6]
Hello, as title, it would be great to upgrade the bootstrap framework from 3 to 4 for creating a more complex layout if possible.

**Comment by mshossain110** [comment]
I will take the necessary steps to upgrade bootstrap 4 and Laravel 6 very soon.  please contribute to upgrading it. 
Thanks

**Comment by key60529** [comment]
> I will take the necessary steps to upgrade bootstrap 4 and Laravel 6 very soon. please contribute to upgrading it.
> Thanks

Okay, I will try to create a PR after upgrade to the Bootstrap 4😁

**Comment by mshossain110** [comment]
Hello, I upgraded the application in Laravel 7.  it is already in Bootstrap 4. I think you will be like the application. also, I am continuously developing now.
